INSERT INTO admin_settings (key, value) VALUES
  ('asset.BTC.enabled', 'true'::jsonb),
  ('asset.BTC.label', '"BTC"'::jsonb),
  ('asset.ETH.enabled', 'true'::jsonb),
  ('asset.ETH.label', '"ETH"'::jsonb),
  ('asset.USDT_TRC20.enabled', 'true'::jsonb),
  ('asset.USDT_TRC20.label', '"USDT (TRC20)"'::jsonb),
  ('asset.USDT_ERC20.enabled', 'true'::jsonb),
  ('asset.USDT_ERC20.label', '"USDT (ERC20)"'::jsonb),
  ('asset.USD.enabled', 'true'::jsonb),
  ('asset.USD.label', '"USD"'::jsonb),
  ('asset.EUR.enabled', 'true'::jsonb),
  ('asset.EUR.label', '"EUR"'::jsonb),
  ('asset.GBP.enabled', 'true'::jsonb),
  ('asset.GBP.label', '"GBP"'::jsonb),
  ('asset.STOCKS.enabled', 'true'::jsonb),
  ('asset.STOCKS.label', '"STOCKS"'::jsonb),
  ('wallet.depositAddress.BTC', '""'::jsonb),
  ('wallet.depositAddress.ETH', '""'::jsonb),
  ('wallet.depositAddress.USDT_TRC20', '""'::jsonb),
  ('wallet.depositAddress.USDT_ERC20', '""'::jsonb),
  ('wallet.depositAddress.USD', '""'::jsonb),
  ('wallet.depositAddress.EUR', '""'::jsonb),
  ('wallet.depositAddress.GBP', '""'::jsonb),
  ('wallet.depositAddress.STOCKS', '""'::jsonb)
ON CONFLICT (key) DO NOTHING;
